type: robot_local_control_components/NavigationComponent
desired_freq: 1.0

check_sensors_state: false
check_localization_state: false
has_safety_laser: false
safety_laser_mode_allowed: false
charge_disable_procedures: false
uncharge_procedure_name: UnchargeComponent
goto_procedure_name: GoToComponent

#components: [GoToComponent, ChargeComponent, UnchargeComponent, MoveComponent]
components:
 - GoToComponent

GoToComponent:
  type: robot_local_control_procedures/GoToMoveBase
  desired_freq: 5.0
  action_namespace: move_base
  global_frame: $(arg prefix)map
  base_frame: $(arg prefix)base_footprint
  default_yaw_tolerance: 0.1 # when goal has orientation. if orientation is invalid, goal tolerance is changed to 3.14
  has_safety_laser: false
  yaw_tolerance: 0.1
  xy_tolerance: 0.15
  preemptable: false
  clear_costmaps_before_send_goal: false
  local_planner_namespace: TebLocalPlannerROS

MoveComponent:
  type: robot_local_control_procedures/Move
  desired_freq: 5.0
  action_namespace: move
  move_state_topic: move/state
  preemptable: false

