global_costmap:
  global_frame: $(arg prefix)map
  robot_base_frame: $(arg prefix)base_footprint
  update_frequency: 5.0
  rolling_window: false
  width: 100.0 # this are overwritten static_layer receives a map
  height: 100.0 # this are overwritten static_layer receives a map
  resolution: 0.05 # this are overwritten static_layer receives a map

  plugins:
    - name: static_map_layer
      type: "costmap_2d::StaticLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"